{"msg":[
    {"name":"name","describe":"姓名","type":"text"},
    {"name":"phone","describe":"手机号","type":"text"},
    {"name":"pic","describe":"二维码","type":"img"}],
    "schedule":[
        {"date":"5月1日","time":"8:00~9:00","event":"吃早饭","address":"餐厅","detail":"二楼"},
        {"date":"5月1日","time":"9:00~10:00","event":"开会","address":"明德楼","detail":"二楼301室"},
        {"date":"5月1日","time":"8:00~9:00","event":"吃早饭","address":"餐厅","detail":"二楼"},
        {"date":"5月1日","time":"8:00~9:00","event":"吃早饭","address":"餐厅","detail":"二楼"}
    ]
}